### ISSUE TITLE
multi-get thrift support?

### ISSUE THREAD

**Issue by beatlevic** [simplereach/helenus#102]
Any plans for adding multi-get thrift support?

**Comment by devdazed** [comment]
Yeah, we have plans to support everything.  The reason why multiget has been put on the backburner is because, due to the non-blocking nature of nodejs it is almost always more performant to send a separate request for each row than to use mget.  The reason behind this is that you are effectively distributing the work of getting the rows to all nodes in your cluster.  Most use [async](https://github.com/caolan/async) to control the flow of getting multiple items at once.

**Comment by beatlevic** [comment]
Thanks. We are indeed also using the async lib to do multiple calls. It is just that we want to do a multiget of 1000 rows, and it seems better to use multiget and have only one outgoing async request with all the results into one response.
