### ISSUE TITLE
No way to know when reconnected

### ISSUE THREAD

**Issue by hmeerlo** [simplereach/helenus#105]
Hi,

am I missing something, or is there no way of knowing whether the connections to cassandra have been restored (other than trying to use the connection)? I get an 'error' event when the connections are gone. Then I redirect my users to a 'sorry system is down' page. But there seems to be no event when the connections are back. Is it useful to add this?

/Herman

**Comment by devdazed** [comment]
currently we don't emit `connect` when connecting to a host. The only time the queries will error due to connections is if you don't have enough connections to make the `CONSISTENCY_LEVE`L requirement.  It's up to the app to decide to drop the CL to make the query.  If there are no hosts available then it will keep trying until it succeeds.

**Comment by hmeerlo** [comment]
Well, my issue is if the entire cassandra cluster is down for some reason. So not just 1 or more nodes. In that case I want to notify my users properly that the system is not functioning, which I can do because of the error emitted. But after that I don't know when to return to normal operation again because it is unknown whether queries will be successful again.

**Comment by asilvas** [comment]
That's not the responsibility of the client. Does a relational database inform you once it comes back online? You have to hit it, to know.

**Comment by devdazed** [comment]
To help, we now emit `connect` once the driver has reconnected.
