### ISSUE TITLE
Exceptions being thrown when callbacks should suffice — intended?

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [simplereach/helenus#133]
Hello :)

I'm getting started with using helenus as a CQL3 driver for Cassandra, and I'm a bit puzzled about the number of exceptions that helenus throws.

For instance, providing an integer for a text field in a pool.cql() call will cause helenus to throw an exception rather than using the callback function to inform about the error. This forces me to wrap the cql() call in a try catch block and duplicate my error handling code (or factor it out).

Seems counter-intuitive considering how node (and libraries in general) handle errors. Also, this sort of error isn't even emitted, so it cannot be acted on by an event listener either.

Is this really the intended behavior, and if so, what is the suggested error handling pattern for working with the helenus driver?

Thanks in advance,
Daniel :)

**Comment by devdazed** [comment]
I think the reason was to let the user know that the error happened before the callback was invoked, for instance, if the error came back in the callback, it would mean that the error is asynchrounous which would be misleading and ultimately lead in an inconsistent API.  

A quick fix would be to add the try..catch in the driver with a `setImmediate` around the callback to ensure that the API remains consistent.  Thoughts?
