### ISSUE TITLE
How to insert an entity containing a collection item, say a set or list?

### ISSUE THREAD

**Issue by raghukanchiraju** [simplereach/helenus#138]
I tried many different ways like Buffer.toString('hex'), set_type_marshal.serialize(data) etc., but all of them failed. There is not much documentation/tutorial available anywhere and this is the last straw.

**Comment by raghukanchiraju** [comment]
This is schema we use 
CREATE TABLE channels (
  id uuid,
  status text,
  created_on timestamp,
  last_active_on timestamp,
  users set < uuid >,
  PRIMARY KEY (id, status)
)

**Comment by devdazed** [comment]
I'm not sure I follow. If you want to insert a collection you just need to create the [proper CQL](http://www.datastax.com/documentation/cql/3.0/cql/cql_reference/update_r.html).  

This seems to work just fine:

``` js
  pool.cql("UPDATE channels SET created_on=dateOf(now()), users = users + {?} WHERE id = ? AND status = ?", [new Helenus.UUID(), new Helenus.UUID(), 'active'], function(err, results){
    if(err){
      throw(err);
    }
  });
```

And if you want to do it as an insert rather than an update:

``` js
  var users = [new Helenus.UUID(), new Helenus.UUID(), new Helenus.UUID()];
  pool.cql("INSERT INTO channels (id, status, created_on, last_active_on, users) VALUES (?, ?, dateOf(now()), dateOf(now()), {?})", [new Helenus.UUID(), 'active', users], function(err, results){
    if(err){
      throw(err);
    }

  });
```

The last example also shows passing multiple values in for the set.

As far as "support", I am always in the [#cassandra](http://webchat.freenode.net/?channels=#cassandra) channel on IRC.
The [Helenus Google Group](https://groups.google.com/forum/#!forum/helenus),  the [mailing list](http://www.mail-archive.com/user@cassandra.apache.org/), and [StackOverflow](http://stackoverflow.com/) are also good sources for help.

**Comment by raghukanchiraju** [comment]
Thank you so much, I'm still figuring out my way around Cassandra. Really appreciate your timely response.
