### ISSUE TITLE
How to escape question marks?

### ISSUE THREAD

**Issue by dmuth** [simplereach/helenus#50]
I know this sounds silly, but is there a way to escape question marks in CQL statements?

Yes, I agree that I should be using parameterized queries but, without going into details, that would be a challenge in my current environment.

Many thanks,

-- Doug

**Comment by devdazed** [comment]
Have you tried it?  If you don't specify arguments, it will not try to replace the `?`.

this seems to work for me

``` javascript
conn.cql("select * from myusers where key='amidoinitrite?'", function(err,row){ 
  console.log(err, row) 
});
```

**Comment by dmuth** [comment]
Oh, that's interesting!  Yes, I ended up having to write code like this:

```
if (args.length) {
   helenus_pool.cql(query, args, cb);
} else {
   helenus_pool.cql(query, cb);
}
```

This is the first time I've had to do this for a database library.  Would it be reason to ask for argument substitution to NOT happen when args is empty?

**Comment by devdazed** [comment]
not really because if someone happens to have no parameters when they were trying to have 1 parameter, the query will pass. If you have too many or too few parameters it is supposed to throw an error.   This is in line with the way the mysql driver as well as many other sql drivers work.

you could probably do something like this:

``` javascript
if(args.length === 0){
  args = undefined;
}

helenus_pool.cql(query, args, cb);
```

**Comment by dmuth** [comment]
Fair enough.  I'll close this one out then.
