### ISSUE TITLE
Counter column values not returning as integers

### ISSUE THREAD

**Issue by jamesbloomer** [simplereach/helenus#61]
Created a table and updated the counter column using the following CQL:

  CREATE TABLE testcount (key varchar PRIMARY KEY, cnt counter)
  UPDATE testcount SET cnt=cnt+1 WHERE key=1

Then reading the value using:

  pool.cql('SELECT cnt FROM testcount', [], function(err, results){
    console.log(results[0].get('cnt'));
  });

..gives the following result:

  { name: 'cnt',
    value: '\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0004',
    timestamp: Fri, 16 Jan 1970 12:43:53 GMT,
    ttl: null }

Is this as expected? I would have thought that the counter value would be returned as an integer whereas it looks like some kind of Buffer. Have tried the core buffer methods but they don't return anything sensible. Running the query in CQLSH shows an integer.

**Comment by devdazed** [comment]
it looks like the driver didn't know how to decode the response properly, which version of C\* are you running?  is this using CQL 3 or CQL 2?

**Comment by calvinfo** [comment]
Whoops, didn't check for CQL support when testing counters.  

The problem seems to come from the fact that thrift returns the counter value as a plain long whereas CQL returns it as a buffer which needs deserialization. I'm not sure why this is exactly.

The simplest fix I see is to set the `CounterColumn` deserializer to be `Deserializers.decodeLong` (fixes CQL) and then add a special case for counters from `Row.fromThrift()` to fix the thrift client.

What are your thoughts @devdazed ?

**Comment by devdazed** [comment]
I think this is the best course of action for now, change the `CounterColumn` deserializer from `IDENTITY` to `Deserializers.decodeLong` and then we can fix the thrift client to check if it is a counter column and ignore deserialization.

**Comment by calvinfo** [comment]
I made the changes we discussed, should be fixed now. Let me know if there's any tests that I missed.

**Comment by jamesbloomer** [comment]
Working great now, thanks.
