### ISSUE TITLE
CQL queries not working properly against Cassandra 1.2

### ISSUE THREAD

**Issue by KhoaVo** [simplereach/helenus#89]
Selects seem to only return primary key columns and 
create and updates return an error that look like

{ [HelenusInvalidRequestException: cannot parse 'foo' as hex bytes] name: 'HelenusInvalidRequestException' }

**Comment by KhoaVo** [comment]
Test table here 

CREATE TABLE test (
  id text PRIMARY KEY,
  name text
)

code executed

 pool.cql("insert into test (id,name) values (?,?)",['bob','dole'],function(e,rows){
        console.log(e);
    });

Error returned
{ [HelenusInvalidRequestException: cannot parse 'dole' as hex bytes] name: 'HelenusInvalidRequestException' }

**Comment by devdazed** [comment]
We will be adding support for 1.2 in the next few days.

**Comment by chris-rock** [comment]
Is it planned to implement maps, sets and lists as well? See here for more details: http://www.datastax.com/dev/blog/cql3_collections

Here is a sample:

CREATE TABLE test (
    id uuid PRIMARY KEY,
    list1 list<varchar>,
    emails set<text>,
    todo map<timestamp, text>
);

INSERT INTO test (id, list1, emails, todo) VALUES ( '3c7f96ed-83ad-43f4-aa4e-c897dba53eaf', ['123', 'abv'] , {'email1@example.com', 'email2@example.com'}, { '2012-9-24' : 'enter mordor','2012-10-2 12:00' : 'throw ring into mount doom' });

I have not fully understood how thrift works yet. I rebuild the cassandra.js  and cassandra_types.js with the latest cassandra.thrift from version 1.2.0. So that works fine on my side. Since requests are handled in cassandra.js, I was thinking everything should work fine after updating. But currently the above posted sample just works cqlsh with cql3 activated. I have also activated cqlVersion : '3.0.0' in my pool config.

**Comment by devdazed** [comment]
Yes, the new items use the new CQL binary protocol.  We are currently working on implementing the protocol and still allowing the use of the Thrift enabled services.

**Comment by chris-rock** [comment]
Question: Are you going to implement basic cql3 via thrift or do you use the new protocol https://git-wip-us.apache.org/repos/asf?p=cassandra.git;a=blob_plain;f=doc/native_protocol.spec;hb=refs/heads/cassandra-1.2?

**Comment by devdazed** [comment]
I want to do both, we still need to discuss a good way to go about it. I'm thinking auto-detecting if the new binary protocol exists and just opening the same number of connections to that.  Then using it where appropriate.  I think getting this out with basic thrift support is a first-step though.

**Comment by chris-rock** [comment]
sounds greate. I consider the thrift api more stable at the moment. does it make sense if we focus on implementing cql3 for thrift first?  I think more work is involved in getting the new protocol stable.

**Comment by devdazed** [comment]
absolutely.  I think you're right

**Comment by devdazed** [comment]
closed with #92
