### ISSUE TITLE
CQL is Broken on C* < 1.2.0

### ISSUE THREAD

**Issue by devdazed** [simplereach/helenus#93]
Because of the new "execute_cql3_query" introduced in the latest build of the thrift client, all CQL commands in C\* < 1.2.0 are no longer working.

**Comment by devdazed** [comment]
actually, it is just broken for 1.1.x, it seems that 1.0.x works.

**Comment by chris-rock** [comment]
I assume we only talk about cql3 queries right? cql2 queries cannot be affected.

**Comment by devdazed** [comment]
yeah, in the old thrift there was no `execute_cql3_query` it was just `execute_cql_query`. I did some version checking to check it for now, but we may want something better, like feature checking.

**Comment by devdazed** [comment]
i was also thinking that we may want to check the version running on the server and load that version of the thrift generated code.  This may be a cleaner more suitable approach that will help us support future versions after features have been deprecated.

**Comment by chris-rock** [comment]
I agree with you. I was thinking about your implemented approach as well. Well done. Regarding the second point.: It may makes sense to implement such version loading in future versions. But as long as Cassandra thrift protocol keeps compatible and api keeps stable, we shouldn't do this. I would expect, that such approach leads to more complexity, additional performance issues (e.g. due to code loading) and maybe even more bugs.

**Comment by flocks** [comment]
Hello guys, 

I'm using the last version of helenus and a Cassandra Server 1.2.1. 
In the connectionPool config, i set the cqlVersion paramater to '2.0.0'. 

While I'm able to connect properly to the server, the requests I make, does not return any results.

Do you have some idea which could help me ?  Do you want some code I wrote ?

**Comment by devdazed** [comment]
go ahead and create a new issue with code to be able to reproduce
